apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registration
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration
        image: tachion2018registry.azurecr.io/docker-images/registration:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: registration
spec:
  ports:
  - port: 80
  selector:
    app: registration
---
apiVersion: v1
kind: Service
metadata:
  name: registrationlb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: registration