apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: issue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: issue
    spec:
      containers:
      - name: issue
        image: tachion2018registry.azurecr.io/docker-images/issue:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: issue
spec:
  ports:
  - port: 80
  selector:
    app: issue
---
apiVersion: v1
kind: Service
metadata:
  name: issuelb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: issue