apiVersion: v1
kind: Service
metadata:
  name: pasangularapp
  labels:
    app: pasangularapp
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: pasangularapp
---
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pasangularapp
  namespace: default
  labels:
    app: pasangularapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pasangularapp
  template:
    metadata:
      name: pasangularapp
      labels:
        app: pasangularapp
    spec:
      containers:
      - name: pasangularapp
        image: tachion2018registry.azurecr.io/docker-images/pasangularapp:v1
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler